# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c3837c3ea8289e0a3df09eb1971fde61f2cbcc06a0e7c88c2d99074d3f2b2112521a6b8c7a72e5d90ac9bffd59581ce494b1fa4a1c55deeb29a0541e6c34b7

test:
  secret_key_base: 2f0586c78eb24ad453dbed5b3425ea08c408f68486335f703379eaff9a399b8de51dbfad2233e75e7dadc79c60299f419c2b6c77230907d50c10f0de709c7972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
